// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgB45BJoQId_GQndmo1rVsBV47GaRM3sg',
    appId: '1:756900196286:web:d7270165a2d070950813ef',
    messagingSenderId: '756900196286',
    projectId: 'tcc-udesc-enchentes',
    authDomain: 'tcc-udesc-enchentes.firebaseapp.com',
    storageBucket: 'tcc-udesc-enchentes.firebasestorage.app',
    measurementId: 'G-KVZZXKBQ8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSPk-FiBv_-a9QITwm6txCewxLMMiG4qM',
    appId: '1:756900196286:android:486401bc26273fa00813ef',
    messagingSenderId: '756900196286',
    projectId: 'tcc-udesc-enchentes',
    storageBucket: 'tcc-udesc-enchentes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIimxiWYwqcOCqkDYBLO-BS5346qRuJl0',
    appId: '1:756900196286:ios:5101848ad53272b90813ef',
    messagingSenderId: '756900196286',
    projectId: 'tcc-udesc-enchentes',
    storageBucket: 'tcc-udesc-enchentes.firebasestorage.app',
    iosBundleId: 'br.com.jpedroparro.petguiaEnchentes',
  );
}
